### ISSUE TITLE
create-new-jira-version goal does not work with jira 6.1.9

### ISSUE THREAD

**Issue by tmortagne** [schrepfler/jira-maven-plugin#10]
Getting the following error:

```
[ERROR] Error when executing mojo
com.atlassian.jira.rest.client.RestClientException: org.codehaus.jettison.json.JSONException: A JSONObject text must begin with '{' at character 1 of <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://jira.xwiki.org/rest/api/latest/version">here</a>.</p>
</body></html>

	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:167)
	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:159)
	at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:48)
	at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:12)
	at com.atlassian.util.concurrent.Promises$Of$3.apply(Promises.java:285)
	at com.atlassian.util.concurrent.Promises$2.onSuccess(Promises.java:162)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:799)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:262)
	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:134)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:175)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
	at com.atlassian.util.concurrent.Promises$Of$3.apply(Promises.java:285)
	at com.atlassian.util.concurrent.Promises$2.onSuccess(Promises.java:162)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:799)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:262)
	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:134)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:175)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:46)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable$1.run(SettableFuturePromiseHttpPromiseAsyncClient.java:197)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:90)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:192)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.jettison.json.JSONException: A JSONObject text must begin with '{' at character 1 of <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://jira.xwiki.org/rest/api/latest/version">here</a>.</p>
</body></html>

	at org.codehaus.jettison.json.JSONTokener.syntaxError(JSONTokener.java:439)
	at org.codehaus.jettison.json.JSONObject.<init>(JSONObject.java:169)
	at org.codehaus.jettison.json.JSONObject.<init>(JSONObject.java:266)
	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient.extractErrors(AbstractAsynchronousRestClient.java:202)
	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:164)
	... 26 more
```

**Comment by schrepfler** [comment]
Hi Thomas, 
How do you propose we can test this? I don't have access to this version of JIRA. Does it even support the REST API?

**Comment by tmortagne** [comment]
> Does it even support the REST API?

release-jira-version works fine with the exact same setup (I just change the goal and make sure the version does not already exist) so I guess it means it does. I reproduced it with something very close to https://github.com/xwiki-contrib/parent/blob/master/parent-commons/pom.xml#L135 (just a different goal). This is a parent pom supposed to be used by XWiki non-core extensions, goal being to make things easier for XWiki contributors (I was think about automatically create if it does not already exist and release the version to make sure the jira project the extension is in sync).

> How do you propose we can test this?

I could create some test project on http://jira.xwiki.org in which you are allowed to create versions if you want to debug it. I can also test snapshots you you prefer but the first solution is probably safer to make sure I'm not doing crap :)

**Comment by tmortagne** [comment]
I tried again with 0.5 and it works well.
